### ISSUE TITLE
Hover message requires prompt to exit

### ISSUE THREAD

**Issue by rkshthrmsh** [seblj/nvim-echo-diagnostics#7]
Hi @seblj, thanks for this wonderful plugin. I have been looking around for something to unify LSP and ALE messages in the command line on hover. However, unlike ALE messages that just appear on cursor hover / pass, the LSP messages open a window that needs a prompt to exit. Is there anyway to change that?

**Comment by seblyng** [comment]
Thanks for the kind words! Is it the prompt to press enter to continue? If that's the case, then it is a bug. That prompt should not appear, and I thought I had fixed the bugs related to that, but apparently not😅 Do you have a file with some error that makes it reproducible for me so that I can debug what could be the issue?

**Comment by rkshthrmsh** [comment]
Hy @seblj, I updated a few things before responding here, and it appears that one of the updates has fixed this issue. Will be closing this now. Thanks again!
